apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-azm7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-with-depl-tenant/appstudio/dc-metro-map-azm7@sha256:14022b6eb4cf55ff434e3105066b91fb7ef855c9997f538370d4e4ed2b93d9fc
        name: my-nodejs
        resources: {}
status: {}
